tips/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

app_name = 'tips'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^section/(?P<section_id>\d+)$', TemplateView.as_view(template_name='index.html'), name='index'),
]

tipsandtricks/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers
from tips import views

router = routers.DefaultRouter()
router.register(r'tips', views.TipViewSet)
router.register(r'tricks', views.TrickViewSet)
router.register(r'sections', views.SectionViewSet)
router.register(r'tipstricks/(?P<section_id>\d+)', views.TipTricksList, 'tiptricks')

urlpatterns = [
    url(r'^tips/', include('tips.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

tips/models.py
from django.db import models

class Section(models.Model):

    title = models.CharField(max_length=20,
                                     help_text="Section title")

    def __str__(self):
        return self.title

class Tip(models.Model):
    title = models.CharField(max_length=20,
                             help_text="Tip title")

    notes = models.CharField(max_length=200,
                             help_text="Tip notes")

    section = models.ForeignKey(Section)

    def __str__(self):
        return self.title

class Trick(models.Model):

    command = models.CharField(max_length=50,
                               help_text="Tip command")

    tip = models.ForeignKey(Tip, related_name='tricks')

    def __str__(self):
        return self.command

tips/views.py
from .models import Section, Tip, Trick

from rest_framework import viewsets
from .serializers import SectionSerializer, TipSerializer, TrickSerializer, TipTrickSerializer

class TipTricksList(viewsets.ModelViewSet):
    """
    Get tips and tricks for display.
    """
    serializer_class = TipTrickSerializer

    def get_queryset(self):
        id = self.kwargs['section_id']
        return Tip.objects.filter(section=id)

class SectionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Sections to be viewed or edited.
    """
    queryset = Section.objects.order_by('title')
    serializer_class = SectionSerializer

class TipViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Tips to be viewed or edited.
    """
    queryset = Tip.objects.all()
    serializer_class = TipSerializer

class TrickViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Tricks to be viewed or edited.
    """
    queryset = Trick.objects.all()
    serializer_class = TrickSerializer

templates/base.html
{% load pipeline %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Tips and Tricks{% endblock %}</title>
    <!-- styles -->
    {% stylesheet 'site_css' %}

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
 
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div id="page" class="container">
    <header>
      {% block header %}{% endblock %}
      <nav>{% block navigation %}{% endblock %}</nav>
    </header>
    <section>
            <div id="container" class="vertical-spacing">
              {% block content %}{% endblock %}
            </div>
    </section>
    <footer>
              {% block footer %}{% endblock %}
    </footer>
  </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load pipeline %}

{% block title %}MySite{% endblock %}

{% block content %}
<!-- JavaScript scripts -->
{% javascript 'index_js' %}
{% endblock %}

tips/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Tips and Tricks{% endblock %}</title>
    <link rel="stylesheet" href="/static/tips/style.css" type="text/css" media="screen" />

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
 
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div id="page" class="container">
		<header>
			{% block header %}{% endblock %}
			<nav>{% block navigation %}{% endblock %}</nav>
		</header>
		<section>
            <div id="container" class="vertical-spacing">
	    	{% block content %}{% endblock %}
            </div>
		</section>
		<footer>
            {% block footer %}{% endblock %}
        </footer>
	</div>
</body>
</html>

tips/templates/tips/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
{% if section_list %}
    {% for section in section_list %}
        <div class="col-md-4 div-padded">
            <a class="btn btn-primary btn-lg btn-block outline" href="{% url 'tips:section' section.id %}">   
                {{ section.title }}
            </a>
        </div>
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}
    </div><div class="row">
    {% endif %}
    {% endfor %}
{% else %}
    <div class="col-md-12 div-padded">
        There are no sections yet.
    </div>
{% endif %}
</div>

{% endblock %}

tips/templates/tips/section.html
{% extends "base.html" %}

{% load filters %}

{% block content %}

{% if tips %}
    {% for tip in tips %}
    <div class="panel panel-default">
        <div class="panel-heading">  
            {{ tip.title }}
        </div>
        <div class="panel-body lead">
            {{ tip.notes }}
        </div>
        {% if tips %}
        <ul class="list-group">
        {% for trick in tricks|for_tip:tip %}
            <li class="list-group-item">
                <code>{{ trick.command }}</code>
            </li>
        {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% endfor %}
{% else %}
    <div class="row">
        <div class="col-md-12 div-padded">
            There are no tips yet.
        </div>
    </div>
{% endif %}
<a class="btn btn-default" href="{% url 'tips:index' %}">
    Back
</a>

{% endblock %}